CONFIG_I2C=y
CONFIG_I2C_NRFX=y
CONFIG_PINCTRL=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_SENSOR=y
CONFIG_PAT9125=y

# USB logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=4

# Zephyr shell for interactive I2C diagnosis (DTR issue workaround)
CONFIG_SHELL=y
CONFIG_I2C_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
