name: Draw ZMK keymaps
concurrency:
  group: zmk-generated-outputs-${{ github.ref }}
  cancel-in-progress: false
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Build ZMK firmware
    types:
      - completed
  push:
    paths:
      - "keymap-drawer/config.yaml"
      - ".github/workflows/draw-keymap.yml"

jobs:
  draw:
    if: >-
      github.event_name != 'workflow_run' ||
      (github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main')
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      commit_message: "[Draw] Update MeKaBu keymap drawing"
      amend_commit: false
      install_branch: "main"
      keymap_patterns: "config/*.keymap"
      json_path: "config"
      config_path: keymap-drawer/config.yaml
      output_folder: keymap-drawer
      destination: "both"
      parse_args: ""  # map of extra args to pass to `keymap parse`, e.g. "corne:'-l Def Lwr Rse' cradio:''"
      draw_args: "MKB:'-j config/MKB.json'"
